export const exceptions = {
    "country": "Countries",
    "province": "Provinces",
    "district": "Districts",
    "city": "Cities",
    "department": "Departments",
    "designation": "Designations",
    "domicile": "Domiciles",
    "employementtype": "Employement Types",
    "hrservicestatus": "Hr Service Status",
    "hr-service-type": "Hr Service Types",
    "hr-termination-type": "Hr Termination Types",
    "status": "Status",
    "organization": "Organizations",
    "caste": "Castes",
    "sections": "Under Sections",
    "bannedorganizations": "Banned Organizations",
    "crimetype": "Crime Types",
    "remissiontype": "Remission Types",
    "courttype": "Court Types",
    "hospital": "Hospitals",
    "court": "Courts",
    "judgetype": "Judge Types",
    "judge": "Judges",
    "policestation": "Police Stations",
    "arv": "Arv's",
    "remission": "Remissions",
    "vaccination": "Vaccinations",
    "disease": "Diseases",
    "medicinetype": "Medicine Types",
    "medicine": "Medicines",
    "outsidehospitals": "Outside Hospitals",
    "prisontype": "Prison Types",
    "prisonertype": "Prisoner Types",
    "employee": "Employees",
    "enclosure": "Prison Enclosures",
    "prisonbarracks": "Prison Barracks",
    "prisonersubtype": "Prisoner Sub Types",
    "releasetype": "Release Types",
    "act": "Acts",
    "offencetype": "Offence Types",
    "inprisonoffences": "In Prison Offences",
    "religion": "Religions",
    "sect": "Sects",
    "gender": "Genders",
    "bloodgroup": "Blood Groups",
    "maritalstatus": "Marital Status",
    "narcoticstatus": "Narcotic Status",
    "nationality": "Nationalities",
    "occupation": "Occupations",
    "language": "Languages",
    "educationlkpt": "Educations",
    "educationtypelkpt": "Education Types",
    "relationshiptypes": "Relationship Types",
    "leavetypes": "Leave Types",
    "inventorytype": "Inventory Types",
    "inventory": "Inventories",
    "authorityTypes": "Authorities"
};
	  