// Get Lookups
export const lookupName = {
	country: '/services/app/AddressLkpt/GetAllCountry',
	caste: '/services/app/PersonalInfoLkpt/GetAllCaste',
	religion: '/services/app/ReligionLkpt/GetAllReligion',
	designation: '/services/app/AdminLkpt/GetAllDesignation', 
	province: '/services/app/AddressLkpt/GetAllProvince',
	// prisoner: '/services/app/PrisonerLkpt/GetAllCheckInOut',
	prisonType: '/services/app/PrisonLkpt/GetAllPrisonTypes',
	prison: '/services/app/PrisonLkpt/GetAllPrison',
	court: '/services/app/CourtLkpt/GetAllCourt',
	courtType: '/services/app/CourtLkpt/GetAllCourtType',
	crimeType: '/services/app/CaseLkpt/GetAllCrimeTypes',
	occupation: '/services/app/PersonalInfoLkpt/GetAllOccupation',
	judgeType: '/services/app/CourtLkpt/GetAllJudgeType',
	disease: '/services/app/MedicalLkpt/GetAllDisease',
	prisonerType: '/services/app/PrisonerLkpt/GetAllPrisonerType',
	prisonerSubType: '/services/app/PrisonerLkpt/GetAllPrisonerSubType',
	remissionType: '/services/app/CaseLkpt/GetAllRemissionType',
	offenceType: '/services/app/OffenseTypeLkpt/GetAllOffenseType',
	releaseType: '/services/app/CaseLkpt/GetAllReleaseType',
	policeStation: '/services/app/CourtLkpt/GetAllPoliceStation',
	medicineType: '/services/app/MedicalLkpt/GetAllMedicineType',
	medicine: '/services/app/MedicalLkpt/GetAllMedicine',
	facilitationCenters: '/services/app/MedicalLkpt/GetAllFacilitationCenters',
	medicalTests: '/services/app/MedicalLkpt/GetAllMedicalTests',
	medicalTestsResults: '/services/app/MedicalLkpt/GetAllMedicalTestsResults',
	outsideHospitals: '/services/app/MedicalLkpt/GetAllOutsideHospitals',
	'manage-roles': '/services/app/Role/GetAll',
	// checkInOut: '/services/app/PrisonerLkpt/GetAllCheckInOut',
	prisonerCategory: '/services/app/PrisonerLkpt/GetAllPrisonerCategory',
	acts: '/services/app/CaseLkpt/GetAllActs',
	sections: '/services/app/CaseLkpt/GetAllActsSections',
	district: '/services/app/AddressLkpt/GetAllDistrict',
	city: '/services/app/AddressLkpt/GetAllCity',
	departments: '/services/app/AdminLkpt/GetAllDepartment',
	employementType: '/services/app/AdminLkpt/GetAllEmploymentType',
	hrServiceStatus: '/services/app/AdminLkpt/GetAllHrServiceStatus',
	'hr-service-type': '/services/app/AdminLkpt/GetAllHrServiceType',
	'hr-termination-type': '/services/app/AdminLkpt/GetAllHrTerminationType',
	bannedOrganizations: '/services/app/CaseLkpt/GetAllBannedOrganizations',
	judge: '/services/app/CourtLkpt/GetAllJudge',
	// outinReason: '/services/app/PrisonerLkpt/GetAllCheckInOutReasonLkpt',
	checkReason: '/services/app/CaseLkpt/GetAllCheckReasons',
	ageCategory: '/services/app/PersonalInfoLkpt/GetAllAgeCategory',
	caste: '/services/app/PersonalInfoLkpt/GetAllCaste',
	gender: '/services/app/PersonalInfoLkpt/GetAllGender',
	MaritalStatus: '/services/app/PersonalInfoLkpt/GetAllMaritalStatus',
	NarcoticStatus: '/services/app/PersonalInfoLkpt/GetAllNarcoticStatus',
	Nationality: '/services/app/PersonalInfoLkpt/GetAllNationality',
	Occupation: '/services/app/PersonalInfoLkpt/GetAllOccupation',
	Relationships: '/services/app/PersonalInfoLkpt/GetAllRelationships',
	Language: '/services/app/PersonalInfoLkpt/GetAllLanguage',
	EducationLKPT: '/services/app/EducationLkpt/GetAllEducationLkpt',
	EducationTypeLkpt: '/services/app/EducationLkpt/GetAllEducationTypeLkpt',
	ReleaseType: '/services/app/CaseLkpt/GetAllReleaseType',
	Enclosure: '/services/app/PrisonLkpt/GetAllPrisonCircle',
	PrisonBarracks: '/services/app/PrisonLkpt/GetAllPrisonBarracks',
	PrisonBarrackTypes: '/services/app/PrisonLkpt/GetAllPrisonBarrackTypes',
	bloodGroup: '/services/app/MedicalLkpt/GetAllBloodGroup',
	inventory: '/services/app/AdminLkpt/GetAllInventory',
	inventoryType: '/services/app/AdminLkpt/GetAllInventoryType',
	sect: '/services/app/ReligionLkpt/GetAllSect',
	vaccinations: '/services/app/MedicalLkpt/GetAllVaccinationsLkpt',
	getAllMedicineProvidedByeList: '/services/app/MedicalLkpt/GetAllMedicineProvidedByeList',
	donors: '/services/app/DonorName/GetAll',
	leaveTypes: '/services/app/LeaveType/GetAll',
	quantityTypes: '/services/app/Medicine/GetAllQuantityTypes',
	roles: '/services/app/User/GetRoles',
	domicile: '/services/app/AddressLkpt/GetAllDomicile',
	hospitalAdmissionTypes: '/services/app/MedicalLkpt/GetAllHospitalAdmissionTypes',
	doctors: '/services/app/EmployeeAppServices/GetAllDoctors',
	transferStatus: '/services/app/CaseLkpt/GetAllTransferStatus',
	checkStatus: '/services/app/CaseLkpt/GetAllCheckStatus',
	caseStatus: '/services/app/CaseLkpt/GetAllCaseStatus',
	inPrisonOffences: '/services/app/OffenseLkpt/GetAllOffenseLkpt',
	crimeTypes: '/services/app/CaseLkpt/GetAllCrimeTypes',
	dayParts: '/services/app/LeaveType/GetAllDayParts',
	allEmployees: '/services/app/EmployeeAppServices/GetAllEmployee',
	policeOfficers: '/services/app/Darban/GetAllPoliceOfficers',
	relationshipTypes: '/services/app/RelationshipTypeLkpt/GetAllRelationshipType',
	remissionTypes: '/services/app/CaseLkpt/GetAllRemissionTypes',
	remission: '/services/app/CaseLkpt/GetAllRemission',
	authorityTypes: '/services/app/CaseLkpt/GetAllAuthorityType',
};

// save lookups
export const saveLookupName = {
	country: '/services/app/AddressLkpt/CreateOrEditCountry',
	caste: '/services/app/PersonalInfoLkpt/CreateOrEditCaste',
	religion: '/services/app/ReligionLkpt/CreateOrEditReligion',
	designation: '/services/app/AdminLkpt/CreateOrEditDesignation',
	prisoner: '/services/app/PrisonerLkpt/CreateOrEditCheckInOut',
	prisonType: '/services/app/PrisonLkpt/CreateOrEditPrisonTypes',
	prison: '/services/app/PrisonLkpt/CreateOrEditPrison',
	province: '/services/app/AddressLkpt/CreateOrEditProvince',
	court: '/services/app/CourtLkpt/CreateOrEditCourt',
	courtType: '/services/app/CourtLkpt/CreateOrEditCourtType',
	crimeType: '/services/app/CaseLkpt/CreateOrEditCrimeTypes',
	occupation: '/services/app/PersonalInfoLkpt/CreateOrEditOccupation',
	judgeType: '/services/app/CourtLkpt/CreateOrEditJudgeType',
	disease: '/services/app/MedicalLkpt/CreateOrEditDisease',
	prisonerType: '/services/app/PrisonerLkpt/CreateOrEditPrisonerType',
	prisonerSubType: '/services/app/PrisonerLkpt/CreateOrEditPrisonerSubType',
	checkInOut: '/services/app/PrisonerLkpt/CreateOrEditCheckInOut',
	prisonerCategory: '/services/app/PrisonerLkpt/CreateOrEditPrisonerCategory',
	remissionType: '/services/app/CaseLkpt/CreateOrEditRemissionType',
	offenceType: '/services/app/OffenseTypeLkpt/CreateOrEditOffenseType',
	policeStation: '/services/app/CourtLkpt/CreateOrEditPoliceStation',
	medicineType: '/services/app/MedicalLkpt/CreateOrEditMedicineType',
	medicine: '/services/app/MedicalLkpt/CreateOrEditMedicine',
	facilitationCenters:
		'/services/app/MedicalLkpt/CreateOrEditFacilitationCenters',
	medicalTests: '/services/app/MedicalLkpt/CreateOrEditMedicalTests',
	medicalTestsResults:
		'/services/app/MedicalLkpt/CreateOrEditMedicalTestsResults',
	outsideHospitals: '/services/app/MedicalLkpt/CreateOrEditOutsideHospitals',
	'manage-roles': '/services/app/Role/Create',
	acts: '/services/app/CaseLkpt/CreateOrEditActs',
	sections: '/services/app/CaseLkpt/CreateOrEditActsSections',
	district: '/services/app/AddressLkpt/CreateOrEditDistrict',
	city: '/services/app/AddressLkpt/CreateOrEditCity',
	departments: '/services/app/AdminLkpt/CreateOrEditDepartment',
	employementType: '/services/app/AdminLkpt/CreateOrEditEmploymentType',
	hrServiceStatus: '/services/app/AdminLkpt/CreateOrEditHrServiceStatus',
	'hr-service-type': '/services/app/AdminLkpt/CreateOrEditHrServiceType',
	'hr-termination-type':
		'/services/app/AdminLkpt/CreateOrEditHrTerminationType',
	bannedOrganizations:
		'/services/app/CaseLkpt/CreateOrEditBannedOrganizations',
	judge: '/services/app/CourtLkpt/CreateOrEditJudge',
	outinReason: '/services/app/PrisonerLkpt/CreateOrEditCheckInOutReasonLkpt',
	ageCategory: '/services/app/PersonalInfoLkpt/CreateOrEditAgeCategory',
	caste: '/services/app/PersonalInfoLkpt/CreateOrEditCaste',
	gender: '/services/app/PersonalInfoLkpt/CreateOrEditGender',
	MaritalStatus: '/services/app/PersonalInfoLkpt/CreateOrEditMaritalStatus',
	NarcoticStatus: '/services/app/PersonalInfoLkpt/CreateOrEditNarcoticStatus',
	Nationality: '/services/app/PersonalInfoLkpt/CreateOrEditNationality',
	Occupation: '/services/app/PersonalInfoLkpt/CreateOrEditOccupation',
	Relationships: '/services/app/PersonalInfoLkpt/CreateOrEditRelationships',
	Language: '/services/app/PersonalInfoLkpt/CreateOrEditLanguage',
	EducationLKPT: '/services/app/EducationLkpt/CreateOrEditEducationLkpt',
	EducationTypeLkpt: '/services/app/EducationLkpt/CreateOrEditEducationTypeLkpt',
	ReleaseType: '/services/app/CaseLkpt/CreateOrEditReleaseType',
	Enclosure: '/services/app/PrisonLkpt/CreateOrEditPrisonCircle',
	PrisonBarracks: '/services/app/PrisonLkpt/CreateOrEditPrisonBarracks',
	PrisonBarrackTypes: '/services/app/PrisonLkpt/CreateOrEditPrisonBarrackTypes',
	bloodGroup: '/services/app/MedicalLkpt/CreateOrEditBloodGroup',
	inventory: '/services/app/AdminLkpt/CreateOrEditInventory',
	inventoryType: '/services/app/AdminLkpt/CreateOrEditInventoryType',
	sect: '/services/app/ReligionLkpt/CreateOrEditSect',
	vaccinations: '/services/app/MedicalLkpt/CreateOrEditVaccinationsLkpt',
	donors: '/services/app/DonorName/CreateOrEdit',
	domicile: '/services/app/AddressLkpt/CreateOrEditDomicile',
	leaveTypes: '/services/app/LeaveType/CreateOrEdit',
	inPrisonOffences: '/services/app/OffenseLkpt/CreateOrEditOffenseLkpt',
	crimeTypes: '/services/app/CaseLkpt/CreateOrEditCrimeTypes',
	relationshipTypes: '/services/app/RelationshipTypeLkpt/CreateOrEditRelationshipType',
	remission: '/services/app/CaseLkpt/CreateOrEditRemission',
	remissionTypes: '/services/app/CaseLkpt/CreateOrEditRemissionType',
	authorityTypes: '/services/app/CaseLkpt/CreateOrEditAuthorityType',


};

// delete lookups
export const deleteLookupName = {
	country: '/services/app/AddressLkpt/DeleteCountry',
	province: '/services/app/AddressLkpt/DeleteProvince',
	caste: '/services/app/PersonalInfoLkpt/DeleteCaste',
	religion: '/services/app/ReligionLkpt/DeleteReligion',
	designation: '/services/app/AdminLkpt/DeleteDesignation',
	prisoner: '/services/app/PrisonerLkpt/DeleteCheckInOut',
	prisonType: '/services/app/PrisonerLkpt/DeletePrisonerType',
	prisonSubType: '/services/app/PrisonerLkpt/DeletePrisonerSubType',
	prisonerCategory: '/services/app/PrisonerLkpt/DeletePrisonerCategory',
	prison: '/services/app/PrisonLkpt/DeletePrison',
	checkInOut: '/services/app/PrisonerLkpt/DeleteCheckInOut',
	court: '/services/app/CourtLkpt/DeleteCourt',
	courtType: '/services/app/CourtLkpt/DeleteCourtType',
	judgeType: '/services/app/CourtLkpt/DeleteJudgeType',
	disease: '/services/app/MedicalLkpt/DeleteDisease',
	prisonerType: '/services/app/PrisonerLkpt/DeletePrisonerType',
	policeStation: '/services/app/CourtLkpt/DeletePoliceStation',
	medicineType: 'services/app/MedicalLkpt/DeleteMedicineType',
	medicine: 'services/app/MedicalLkpt/DeleteMedicine',
	facilitationCenters: '/services/app/MedicalLkpt/DeleteFacilitationCenters',
	medicalTests: '/services/app/MedicalLkpt/DeleteMedicalTests',
	outsideHospitals: '/services/app/MedicalLkpt/DeleteOutsideHospitals',
	medicalTestsResults: '/services/app/MedicalLkpt/DeleteMedicalTestsResults',
	'manage-roles': '/services/app/Role/Delete',
	acts: '/services/app/CaseLkpt/DeleteActs',
	sections: '/services/app/CaseLkpt/DeleteActsSections',
	district: '/services/app/AddressLkpt/DeleteDistrict',
	city: '/services/app/AddressLkpt/DeleteCity',
	departments: '/services/app/AdminLkpt/DeleteDepartment',
	employementType: '/services/app/AdminLkpt/DeleteEmploymentType',
	hrServiceStatus: '/services/app/AdminLkpt/DeleteHrServiceStatus',
	'hr-service-type': '/services/app/AdminLkpt/DeleteHrServiceType',
	'hr-termination-type': '/services/app/AdminLkpt/DeleteHrTerminationType',
	crimeType: '/services/app/CaseLkpt/DeleteCrimeTypes',
	remissionType: '/services/app/CaseLkpt/DeleteRemissionType',
	inPrisonOffences: '/services/app/OffenseLkpt/DeleteOffenseLkpt',
	offenceType: '/services/app/OffenseTypeLkpt/DeleteOffenseType',
	bannedOrganizations: '/services/app/CaseLkpt/DeleteBannedOrganizations',
	judge: '/services/app/CourtLkpt/DeleteJudge',
	outinReason: '/services/app/PrisonerLkpt/DeleteCheckInOutReasonLkpt',
	ageCategory: '/services/app/PersonalInfoLkpt/DeleteAgeCategory',
	caste: '/services/app/PersonalInfoLkpt/DeleteCaste',
	gender: '/services/app/PersonalInfoLkpt/DeleteGender',
	MaritalStatus: '/services/app/PersonalInfoLkpt/DeleteMaritalStatus',
	NarcoticStatus: '/services/app/PersonalInfoLkpt/DeleteNarcoticStatus',
	Nationality: '/services/app/PersonalInfoLkpt/DeleteNationality',
	Occupation: '/services/app/PersonalInfoLkpt/DeleteOccupation',
	Relationships: '/services/app/PersonalInfoLkpt/DeleteRelationships',
	Language: '/services/app/PersonalInfoLkpt/DeleteLanguage',
	EducationLKPT: '/services/app/EducationLkpt/DeleteEducationLkpt',
	EducationTypeLkpt: '/services/app/EducationLkpt/DeleteEducationTypeLkpt',
	ReleaseType: '/services/app/CaseLkpt/DeleteReleaseType',
	Enclosure: '/services/app/PrisonLkpt/DeletePrisonCircle',
	PrisonBarracks: '/services/app/PrisonLkpt/DeletePrisonBarracks',
	PrisonBarrackTypes: '/services/app/PrisonLkpt/DeletePrisonBarrackTypes',
	bloodGroup: '/services/app/MedicalLkpt/DeleteBloodGroup',
	inventory: '/services/app/AdminLkpt/DeleteInventory',
	inventoryType: '/services/app/AdminLkpt/DeleteInventoryType',
	sect: '/services/app/ReligionLkpt/DeleteSect',
	vaccinations: '/services/app/MedicalLkpt/DeleteVaccinationsLkpt',
	relationshipTypes: '/services/app/RelationshipTypeLkpt/DeleteRelationshipType',
	authorityTypes: '/services/app/CaseLkpt/DeleteAuthorityType',

};
